### ISSUE TITLE
Ratio test issue

### ISSUE THREAD

**Issue by angryQRZ** [ysnsonmez/3D-Reconstruction-From-Multiple-Images#1]
Hello,
I am an university student. I have tried your 3D reconstruction code. There is a problem in Match.cpp.
I have no idea why you set "ratio" member in Matcher class as 0.65f. When I changed this value to 0.64f or 0.66f, the output of ply files are totally wrong. Why is that? Thanks!!

**Comment by ysnsonmez** [comment]
Hi,

These values (ratio(0.65f), refineF(true),confidence(0.99), distance(3.0)) are default values on algorithm.

You changed this value to 0.64f or 0.66f, the output of ply files are totally wrong because algorithm wrong working.


These values descriptions;
     float ratio; // max ratio between 1st and 2nd NN
     bool refineF; // if true will refine the F matrix
     double distance; // min distance to epipolar
     double confidence; // confidence level (probability)
